FROM python:3.8-slim
LABEL maintainer="u6k.apps@gmail.com"

WORKDIR /var/myapp
COPY . /var/myapp

RUN apt-get update && \
    apt-get upgrade -y --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install pipenv && \
    pipenv sync

CMD ["pipenv", "scripts"]
